### ISSUE TITLE
Why is `queue` declared outside its for-loop?

### ISSUE THREAD

**Issue by lafrenierejm** [SoWhich/mkron#2]
Why not iterate over `list` and append to `queue` first inside line 54's `for`, then iterate over `queue` immediately?  Doing so would save having to declare `queue` outside the loop, and it would remove the artificial 1-minute delay between starting `mkron` and any jobs actually executing that the code currently inserts.

The iteration over `list` would need to be looking for processes that are to be executed *now* rather than in 1 minute, but that shouldn't be too big of a change in the logic.

**Comment by SoWhich** [comment]
As for the first part, the queue has been replaced with a stack (impliamented with the same list class as allPs) because it's more conservative with memory. Instead of slices constantly being created, copied, and destroyed, all variables related to the processes exist from the beginning and never going out of scope or needing to be re/deallocated.
As to the second point, the original intention was to ensure that the programs were executed as close to on the minute as possible. In retrospect, I needn't have worried about that. It has been done as of the last commit.
